#pragma once

// Imieniny na caly rok - wariant dluzszy, do 4 imion na dzien.
// Tabela ASCII dla fontow e-paper. Zawiera 29 lutego, razem 366 pozycji.
// Aby podlaczyc: #include "imieniny_rok_4.h" i w nameDay() uzyj imieniny4ForDate(month, day).

static const char* const IMIENINY_ROK_4[366] = {
  "Maria, Mieczyslaw, Mieszko, Maslaw",
  "Bazyli, Grzegorz, Izydor, Makary",
  "Arleta, Danuta, Genowefa, Zdzislaw",
  "Angelika, Aniela, Elzbieta, Eugeniusz",
  "Hanna, Edward, Emilian, Szymon",
  "Baltazar, Kacper, Melchior",
  "Lucjan, Julian, Rajmund, Walentyna",
  "Juliusz, Mscislaw, Seweryn, Artur",
  "Marcelina, Marcjanna, Adrian, Julian",
  "Danuta, Waleria, Bonifacy, Dobroslaw",
  "Teodozjusz, Honorata, Matylda, Feliks",
  "Arkadiusz, Benedykt, Rajmund, Greta",
  "Bogumila, Weronika, Bogumil",
  "Hilary, Dobroslaw, Feliks, Nina",
  "Dabrowka, Pawel, Arnold, Izydor",
  "Waldemar, Marceli, Wlodzimierz, Waleria",
  "Marian, Roscislaw, Antoni, Jan",
  "Piotr, Malgorzata, Beatrycze",
  "Marta, Henryk, Mariusz, Erwin",
  "Fabian, Fabiola, Sebastian, Mila",
  "Agnieszka, Jaroslaw, Nora",
  "Anastazy, Wincent, Dominika, Mateusz",
  "Ildefons, Rajmund, Jan, Fernandy",
  "Felicja, Rafal, Franciszek, Robert",
  "Elwira, Pawel, Milosz, Tatiana",
  "Paulina, Polikarp, Tymoteusz, Michal",
  "Ilona, Przybyslaw, Aniela, Jerzy",
  "Agnieszka, Julian, Walery, Karol",
  "Zdzislaw, Franciszek, Jozef, Salomea",
  "Teofil, Maciej, Martyna",
  "Marcela, Marcelina, Ludwika, Ludwik",
  "Seweryn, Brygida, Ignacy, Dobrogniew",
  "Joanna, Maria, Miroslaw, Kornel",
  "Wawrzyniec, Blazej, Oskar, Joanna",
  "Weronika, Mariusz, Andrzej, Jozef",
  "Agata, Adelajda, Agnieszka, Izydor",
  "Dorota, Bogdan, Pawel, Bohdan",
  "Ryszard, Teodor, Romuald, Roman",
  "Hieronim, Sebastian, Piotr, Jan",
  "Eryka, Cyryl, Apolonia, Marian",
  "Maria, Olgierd, Scholastyka, Elwira",
  "Grzegorz, Lucjan, Olgierd, Bernardetta",
  "Radoslaw, Damian, Eulalia, Aleksy",
  "Grzegorz, Katarzyna, Jordan, Leslaw",
  "Cyryl, Metody, Walenty, Walentyna",
  "Jowita, Faustyn, Zygfryd, Klaudia",
  "Danuta, Julian, Szymon, Daniel",
  "Aleksy, Lukasz, Zbigniew, Donat",
  "Szymon, Konstancja, Maksym, Flawian",
  "Arnold, Jozef, Konrad, Henryk",
  "Leon, Ludomil, Ludomila, Ludomir",
  "Eleonora, Robert, Feliks, Fortunat",
  "Marta, Malgorzata, Piotr, Nikifor",
  "Romana, Roman, Damian, Polikarp",
  "Maciej, Marek, Bogusz, Sergiusz",
  "Cezary, Donat, Wiktor, Alma",
  "Miroslaw, Aleksander, Bogumil, Bogumila",
  "Gabriel, Anastazja, Julian, Liwia",
  "Roman, Ludomir, Makary",
  "Lech, Lutomir",
  "Albina, Antonina, Dawid, Radoslaw",
  "Helena, Halszka, Krzysztof, Karol",
  "Maryna, Kunegunda, Tycjan, Kinga",
  "Arkadiusz, Eugeniusz, Kazimierz, Lucja",
  "Adrian, Fryderyk, Teofil, Aurora",
  "Roza, Wiktor, Agnieszka, Jordan",
  "Tomasz, Felicyta, Pawel, Perpetua",
  "Beata, Wincenty, Jan, Julian",
  "Franciszka, Dominik, Katarzyna, Brunon",
  "Cyprian, Aleksander, Marceli, Bozyslawa",
  "Benedykt, Konstanty, Edwin, Ludoslaw",
  "Alojzy, Bernard, Grzegorz, Justyna",
  "Bozena, Krystyna, Patrycja, Marek",
  "Leon, Martyna, Matylda, Lazarz",
  "Longin, Klemens, Ludwika, Delfina",
  "Izabela, Oktawia, Hilary, Henryk",
  "Patryk, Zbigniew, Regina, Gertruda",
  "Cyryl, Edward, Boguchwala, Narcyz",
  "Jozef, Bogdan, Aleksandryna",
  "Klaudia, Eufemia, Wincenty, Maurycy",
  "Lubomir, Lubomira, Benedykt",
  "Katarzyna, Boguslaw, Oktawian, Jagoda",
  "Pelagia, Feliks, Zbyslaw, Konrad",
  "Marek, Gabriel, Gabriela, Katarzyna",
  "Mariola, Wienczyslaw, Maria, Ireneusz",
  "Larysa, Emanuel, Teodor, Tymoteusz",
  "Lidia, Ernest, Jan, Marek",
  "Aniela, Sykstus, Joanna, Antoni",
  "Wiktoryn, Wiktoryna, Helmut, Eustachy",
  "Aniela, Leonard, Amelia, Jan",
  "Beniamin, Balbina, Kordulia, Kornelia",
  "Teodor, Grazyna, Irena, Zygmunt",
  "Wladyslaw, Franciszek, Teodozja, Urban",
  "Ryszard, Irena, Pankracy, Inga",
  "Benedykt, Izydor, Waclaw",
  "Katarzyna, Wincenty, Irena, Kleofas",
  "Izolda, Ireneusz, Celestyna, Wilhelm",
  "Rufin, Donat, Jan, Saturnin",
  "Dionizy, Julia, Cezaryna, January",
  "Maria, Dymitr, Maja, Marceli",
  "Michal, Makary, Terencjusz, Boryslawa",
  "Filip, Leon, Jaromir, Stanislaw",
  "Damian, Juliusz, Zenon, Wiktor",
  "Przemyslaw, Ida, Marcin, Hermenegilda",
  "Berenika, Walerian, Justyna, Bernard",
  "Ludwina, Waclawa, Anastazja, Teodor",
  "Cecylian, Bernadeta, Julia, Ksenia",
  "Rudolf, Robert, Stefan, Anicet",
  "Alicja, Boguslawa, Apoloniusz, Goscislawa",
  "Adolf, Tymon, Wlodzimierz, Konrad",
  "Czeslaw, Agnieszka, Marian, Czech",
  "Bartosz, Feliks, Konrad, Anzelm",
  "Kaja, Lukasz, Leon, Nastazja",
  "Ilona, Jerzy, Wojciech",
  "Aleksy, Horacy, Horacja, Grzegorz",
  "Marek, Jaroslaw",
  "Marzena, Klaudiusz, Maria, Marcelina",
  "Zyta, Teofil, Felicja, Sergiusz",
  "Pawel, Waleria, Ludwik, Piotr",
  "Rita, Donata, Robert, Roberta",
  "Marian, Katarzyna, Ludwik, Pius",
  "Jozef, Jeremiasz, Aniela, Filip",
  "Zygmunt, Atanazy, Anatol, Longina",
  "Maria, Mariola, Ireneusz, Antonina",
  "Monika, Florian, Wladyslaw, Michal",
  "Irena, Waldemar, Iryda, Tamara",
  "Filip, Judyta, Jan, Jakub",
  "Benedykt, Gizela, Elzbieta, Ludomira",
  "Liza, Stanislaw, Wiktor, Marek",
  "Bozydar, Grzegorz, Karolina, Karol",
  "Izydor, Antonina, Symeon, Jan",
  "Iga, Ignacy, Franciszek, Filip",
  "Achilles, Joanna, Dominik, Pankracy",
  "Gloria, Gerwazy, Robert, Serwacy",
  "Bonifacy, Dobieslaw, Wiktor, Maciej",
  "Zofia, Nadzieja, Berta, Izydor",
  "Andrzej, Jedrzej, Wienczyslaw, Malgorzata",
  "Brunon, Paschalis, Weronika, Wiktor",
  "Eryk, Feliks, Aleksander, Jan",
  "Iwo, Piotr, Mikolaj, Celestyna",
  "Aleksander, Bazyli, Bernardyn, Krystyna",
  "Jan, Wiktor, Tymoteusz, Kryspin",
  "Helena, Wieslawa, Julia, Ryta",
  "Emilia, Iwona, Leoncjusz, Michal",
  "Joanna, Zuzanna, Maria, Milena",
  "Borys, Grzegorz, Urban, Magdalena",
  "Filip, Paulina, Marianna, Ewelina",
  "Augustyn, Julian, Jan, Juliusz",
  "Jaromir, Just, Justyna, Wiktor",
  "Magdalena, Bogumila, Teodozja, Urszula",
  "Ferdynand, Karol, Feliks, Jan",
  "Aniela, Petronelia, Kamila, Feliks",
  "Jakub, Justyn, Konrad, Hortensja",
  "Erazm, Marianna, Marcelin, Piotr",
  "Leszek, Tamara, Karol, Klotylda",
  "Franciszek, Karol, Kwiryna, Helga",
  "Walter, Bonifacy, Waleria, Kira",
  "Norbert, Laurenty, Dominika, Bogumila",
  "Robert, Wieslaw, Antoni, Jaroslaw",
  "Medard, Maksym, Seweryn, Adelajda",
  "Anna, Felicjan, Pelagia, Efrem",
  "Bogumil, Malgorzata, Diana",
  "Barnaba, Radomil, Feliks, Benedykt",
  "Janina, Jan, Leon, Leonia",
  "Lucjan, Antoni, Grecja",
  "Bazyli, Eliza, Justyna, Elwira",
  "Wit, Jolanta, Witold, Lotar",
  "Alina, Justyn, Justyna, Aneta",
  "Albert, Ignacy, Laura, Adolf",
  "Marek, Elzbieta, Paula",
  "Gerwazy, Protazy, Romuald, Sylwia",
  "Diana, Bogna, Bogumila, Florentyna",
  "Alicja, Alojzy, Marta, Rudolf",
  "Paulina, Tomasz, Flawiusz, Jan",
  "Wanda, Zenon, Albina",
  "Jan, Danuta, Janina",
  "Lucja, Wilhelm, Dorota, Witold",
  "Jan, Pawel, Paulina, Rudolfina",
  "Maryla, Wladyslaw, Maria, Cyryl",
  "Leon, Ireneusz, Florentyna, Ligia",
  "Piotr, Pawel, Salomea",
  "Emilia, Lucyna, Rajmund, Arnold",
  "Halina, Marian, Otton, Marcin",
  "Jagoda, Urban, Maria, Karina",
  "Jacek, Anatol, Tomasz, Miroslaw",
  "Odon, Malwina, Teodor, Elzbieta",
  "Maria, Antoni, Karolina, Bartlomiej",
  "Gotard, Dominika, Lucja, Teresa",
  "Benedykt, Cyryl, Metody, Estera",
  "Adriana, Eugeniusz, Elzbieta, Edgar",
  "Lukrecja, Weronika, Zenon, Sylwia",
  "Olaf, Witalis, Filip, Amelia",
  "Olga, Kalina, Benedykt, Pelagia",
  "Jan, Brunon, Weronika, Bonifacy",
  "Ernest, Malgorzata, Daniela, Kinga",
  "Bonawentura, Stella, Izabela, Franciszek",
  "Dawid, Henryk, Wlodzimierz, Iga",
  "Eustachy, Maria, Benedykt, Marika",
  "Aneta, Bogdan, Aleksy, Jadwiga",
  "Emil, Erwin, Kamil, Kamila",
  "Wincenty, Wodzislaw, Marcin, Rufin",
  "Czeslaw, Fryderyk, Hieronim, Seweryn",
  "Daniel, Daniela, Dalida, Wiktor",
  "Maria, Magdalena, Albin, Pankracy",
  "Apolinary, Bogna, Brygida, Slawa",
  "Kinga, Krystyna, Olga, Michalina",
  "Walentyna, Krzysztof, Jakub",
  "Anna, Miroslaw, Grazyna, Joachim",
  "Natalia, Lilia, Julia, Celestyn",
  "Ada, Innocenty, Wiktor, Walenty",
  "Olaf, Marta, Ludmila, Maria",
  "Julita, Piotr, Ludomila, Leopold",
  "Ignacy, Lubomir, Helena, Roman",
  "Alfons, Nadia, Piotr, Justyna",
  "Karina, Gustaw, Euzebiusz, Stefan",
  "Lidia, Augustyn, Nikodem, Kamelia",
  "Dominik, Dominika, Jan, Protazy",
  "Oswald, Maria, Stanislawa, Marian",
  "Slawa, Jakub, Oktawian, Stefan",
  "Kajetan, Klaudia, Donata, Dorota",
  "Cyprian, Dominik, Emilian, Iza",
  "Roman, Ryszard, Romuald, Edyta",
  "Bogdan, Borys, Wawrzyniec, Filomena",
  "Klara, Lidia, Zuzanna, Wlodzimierz",
  "Lech, Euzebia, Innocenty, Hilary",
  "Diana, Hipolit, Poncjan, Gertruda",
  "Alfred, Euzebiusz, Maksymilian, Selma",
  "Maria, Napoleon, Stella",
  "Roch, Stefan, Joachim, Nora",
  "Anita, Eliza, Jacek, Joanna",
  "Ilona, Klara, Bronislaw, Helena",
  "Boleslaw, Jan, Boryslaw, Julian",
  "Bernard, Samuel, Sobieslaw, Sabina",
  "Franciszek, Franciszka, Joanna, Pius",
  "Maria, Cezary, Tymoteusz, Zygfryd",
  "Roza, Apolinary, Filip, Mila",
  "Jerzy, Bartlomiej, Bartosz, Emilia",
  "Luiza, Ludwik, Jozef, Patrycja",
  "Maria, Zefiryna, Teresa, Natalia",
  "Monika, Cezary, Jozef, Teodor",
  "Patrycja, Wyszomir, Aleksander, Augustyn",
  "Beata, Jan, Sabina, Flora",
  "Roza, Szczesny, Feliks, Malgorzata",
  "Izabela, Ramona, Bohdan, Rajmund",
  "Idzi, Bronislawa, Belinda",
  "Julian, Stefan, Seweryn, Wilhelm",
  "Izabelia, Szymon, Dorota, Grzegorz",
  "Ida, Lilianna, Rozalia, Roza",
  "Dorota, Wawrzyniec, Teodor, Justyn",
  "Beata, Eugeniusz, Lidia",
  "Regina, Melchior, Domoslawa, Marek",
  "Maria, Adriana, Serafina, Radoslaw",
  "Piotr, Sergiusz, Jacek, Scibor",
  "Lukasz, Mikolaj, Aldona, Mscislaw",
  "Jacek, Dagna, Feliks, Hiacynt",
  "Gwidon, Radzimir, Maria, Sylwina",
  "Eugenia, Aureliusz, Filip, Jan",
  "Roksana, Bernard, Cyprian, Mona",
  "Albin, Albina, Nikodem, Maria",
  "Edyta, Kornel, Korneliusz, Kamila",
  "Franciszek, Hildegarda, Justyn, Justyna",
  "Irma, Jozef, Irena, Stanislaw",
  "January, Konstancja, Teodor, Leopold",
  "Filipina, Eustachy, Euzebia, Faustyna",
  "Jonasz, Mateusz, Miroslaw, Hipolit",
  "Tomasz, Maurycy, Joachim, Milana",
  "Tekla, Boguslaw, Linus, Liwiusz",
  "Gerard, Teodor, Tomira, Tomir",
  "Aurelia, Wladyslaw, Kleofas, Kamila",
  "Justyna, Cyprian, Wawrzyniec, Lucja",
  "Damian, Amadeusz, Kosmo, Mirabela",
  "Luba, Waclaw, Waclawa, Marek",
  "Michal, Michalina, Franciszek, Rafal",
  "Wera, Honoriusz, Hieronim, Wiktor",
  "Danuta, Remigiusz, Teresa, Igor",
  "Teofil, Dionizy, Slawomir, Rachela",
  "Teresa, Heliodor, Gerard, Jan",
  "Rozalia, Edwin, Franciszek, Konrad",
  "Igor, Flawia, Placyd, Apolinary",
  "Artur, Brunon, Fryderyk, Fryderyka",
  "Maria, Marek, Sergiusz, Mirela",
  "Pelagia, Brygida, Waleria, Marcin",
  "Arnold, Dionizy, Ludwik, Wincenty",
  "Paulina, Franciszek, Daniel, Leon",
  "Emil, Aldona, Aleksander, Dobromira",
  "Eustachy, Maksymilian, Edwin, Serafin",
  "Gerald, Edward, Teofil, Honorata",
  "Alan, Bernard, Liwia, Damian",
  "Teresa, Jadwiga, Florentyna, Aurelia",
  "Gawel, Florentyna, Ambrozy, Jadwiga",
  "Malgorzata, Wiktor, Marita, Ignacy",
  "Juliusz, Lukasz, Julian, Bogumil",
  "Pelagia, Piotr, Ziemowit, Jan",
  "Irena, Jan, Kleopatra, Witalis",
  "Urszula, Hilary, Celina, Jakub",
  "Kordula, Filip, Klaudia, Salomea",
  "Marlena, Seweryn, Teodor, Honorata",
  "Rafal, Marcin, Alojzy, Antoni",
  "Daria, Wilhelmina, Wilhelm, Inga",
  "Lucjan, Lucyna, Fabian, Damian",
  "Iwona, Sabina, Wincenty",
  "Szymon, Tadeusz, Serafin, Wioletta",
  "Euzebia, Wioletta, Felicjan, Angela",
  "Zenobia, Przemyslaw, Edmund, Alfons",
  "Urban, Saturnin, August, Augustyn",
  "Julian, Lukasz, Konrad, Seweryn",
  "Bohdana, Bohdan, Bogdan, Tobiasz",
  "Sylwia, Hubert, Rupert, Marcin",
  "Karol, Olgierd, Emeryk, Albertyna",
  "Elzbieta, Slawomir, Dominik, Zachariasz",
  "Feliks, Leonard, Ziemowit, Jacek",
  "Antoni, Zytomir, Ernest, Kalina",
  "Hadriana, Seweryn, Wiktoryn, Wiktoriusz",
  "Ursyn, Teodor, Gracja, Genowefa",
  "Lena, Ludomir, Natalia, Leon",
  "Marcin, Bartlomiej, Teodor, Gertruda",
  "Renata, Witold, Mateusz, Konrad",
  "Mikolaj, Stanislaw, Stanislawa, Benedykt",
  "Roger, Serafin, Emil, Emilia",
  "Albert, Leopold, Artur, Idalia",
  "Gertruda, Edmund, Maria, Malgorzata",
  "Salomea, Grzegorz, Elzbieta, Waleria",
  "Roman, Klaudyna, Anielia, Karolina",
  "Elzbieta, Seweryn, Seweryna, Salomea",
  "Anatol, Sedzimir, Feliks, Rafal",
  "Janusz, Konrad, Albert, Maria",
  "Marek, Cecylia, Wszemila, Stefan",
  "Adela, Klemens, Klementyna, Felicyta",
  "Flora, Emma, Emilia, Chryzogon",
  "Erazm, Katarzyna, Elzbieta, Klemens",
  "Delfina, Sylwester, Konrad, Leonard",
  "Walerian, Wirgiliusz, Maksymilian, Franciszek",
  "Leslaw, Zdzislaw, Jakub, Stefan",
  "Blazej, Saturnin, Fryderyk, Margerita",
  "Maura, Andrzej, Justyna, Justyn",
  "Natalia, Edmund, Eligiusz, Blanka",
  "Balbina, Bibianna, Paulina, Aurelia",
  "Franciszek, Franciszka, Ksawery, Pasjan",
  "Barbara, Krystian, Hieronim, Jan",
  "Saba, Kryspin, Gerard, Sabina",
  "Jarema, Mikolaj, Emilian, Dionizja",
  "Marcin, Ambrozy, Teodor, Agata",
  "Maria, Swiatozar, Klemens, Makary",
  "Wieslaw, Wieslawa, Leokadia, Joanna",
  "Julia, Daniela, Bogdan, Bohdan",
  "Damazy, Waldemar, Daniel, Stefan",
  "Dagmara, Aleksander, Adelaida, Joanna",
  "Lucja, Otylia, Juliusz",
  "Alfred, Izydor, Jan",
  "Nina, Celina, Walerian, Ireneusz",
  "Albina, Zdzislawa, Zdzislaw, Alicja",
  "Olimpia, Lazarz, Jolanta, Florian",
  "Gracjan, Boguslaw, Laurencja, Laura",
  "Gabriela, Grzegorz, Eleonora, Dariusz",
  "Bogumila, Dominik, Juliusz, Zefiryn",
  "Tomasz, Tomislaw, Anastazy, Piotr",
  "Zenon, Honorata, Franciszka, Bozena",
  "Wiktoria, Wiktor, Slawomir, Malgorzata",
  "Adam, Ewa, Irmina",
  "Anastazja, Eulalia, Eugenia, Gloria",
  "Jan, Szczepan, Dionizy, Kaliksta",
  "Teofilia, Godzislaw, Antoni, Zaneta",
  "Jan, Maksym, Cezary, Antoniusz",
  "Dawid, Tomasz, Dominik, Dionizy",
  "Irmina, Eugeniusz, Irma, Seweryn",
  "Melania, Sylwester, Mariusz"
};

static const int IMIENINY4_START_MIESIACA[12] = {
  0, 31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335
};

static const int IMIENINY4_DNI_MIESIACA[12] = {
  31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
};

static const char* imieniny4ForDate(int month, int day) {
  if (month < 1 || month > 12) return "do uzupelnienia";
  if (day < 1 || day > IMIENINY4_DNI_MIESIACA[month - 1]) return "do uzupelnienia";
  return IMIENINY_ROK_4[IMIENINY4_START_MIESIACA[month - 1] + day - 1];
}
